In [2]:
import numpy as np
print(np.random.rand(5, 5))

[[0.82304839 0.98908845 0.53497397 0.65062967 0.6599521 ]
 [0.6447326  0.07202964 0.34493574 0.26194337 0.79875076]
 [0.67484897 0.09242755 0.57279156 0.57910127 0.61306755]
 [0.98792313 0.20839454 0.09021203 0.06385128 0.05275375]
 [0.19015065 0.30098542 0.67823416 0.65155039 0.21485168]]
